<a href="https://colab.research.google.com/github/Manish-2708/pyt_man/blob/main/pythonday1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
print("python , Be good with me")

python , Be good with me


In [37]:
#COMMENTS

In [38]:
#ENTER -It goes to next line within same block
#SHIFT + ENTER - Its execute the code block and goes to next code block
#ALT + ENTER - Its execute these code block and creates new code block
#CTRL + ENTER - IT EXECUTE THIS CODE

In [39]:
# TYPES OF BRACKETS
#[]-Data extraction /Slicing data , lists
#{}-Dictionaries / Sets
#()-Methods /functions , tuples

In [40]:
# DATATYPE
# int
# float
# str
# bool

In [41]:
a = 2

In [42]:
a

2

In [43]:
type(a)

int

In [44]:
b=10.0
b

10.0

In [45]:
type(b)

float

In [46]:
c="Brad"

In [47]:
type(c)

str

In [48]:
d="True"

In [49]:
type(d)

str

In [50]:
10+20

30

In [51]:
20-5

15

In [52]:
60/10

6.0

In [53]:
60*20

1200

In [54]:
64**2

4096

In [55]:
import math

In [56]:
math.sqrt(64)

8.0

In [57]:
round(23)

23

In [58]:
round(22.5)

22

In [59]:
8==8

True

In [60]:
8==9

False

In [61]:
8!=9

True

In [62]:
7<6

False

In [63]:
7<=6

False

In [64]:
True & True

True

In [65]:
True & False

False

In [66]:
False & True

False

In [69]:
(7>6)&(6<3)

False

In [70]:
(7>6)|(6<3)

True

In [71]:
not((7>6)|(6<3))

False

In [74]:
i=0
while i<10:
      print(i)
      i=i+1

0
1
2
3
4
5
6
7
8
9


In [76]:
i=0
while i<10:
      print(i)
      i=i+1
print('Good Job')

0
1
2
3
4
5
6
7
8
9
Good Job


In [77]:
i=0
while i<10:
      print(i)
      i=i+1
      print('Good Job')

0
Good Job
1
Good Job
2
Good Job
3
Good Job
4
Good Job
5
Good Job
6
Good Job
7
Good Job
8
Good Job
9
Good Job


In [78]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [80]:
for i in range(10):
   print(i)

0
1
2
3
4
5
6
7
8
9


In [82]:
list1= ["Brad",1,True]
print(list1)

['Brad', 1, True]


In [83]:
for i in list1:
  print(i)

Brad
1
True


In [84]:
import numpy as np
from numpy.random import randn

In [98]:
x = randn()
x

-0.3313159790049526

In [106]:
x = randn()
if x > 1 :
  result= "Greater than 1"
print(x)
print(result)

-1.7981919969272853
None


In [107]:
result = None
x = randn()
if x > 1 :
  result= "Greater than 1"
print(x)
print(result)

1.207216481855355
Greater than 1


In [110]:
result = None
x = randn()
if x > 1 :
  result= "Greater than 1"
else:
  result= "Less than 1"
print(x)
print(result)

1.3710070044742817
Greater than 1


In [115]:
result = None
x = randn()
if x > 1 :
  result= "Greater than 1"
else:
  if x>-1:
    result= "Between -1 & 1"
  else:
    result= "Less than -1"
print(x)
print(result)

1.5850220813623428
Greater than 1


In [116]:
result = None
x = randn()
if x > 1 :
  result= "Greater than 1"
elif x>=-1:
    result= "Between -1 & 1"
else:
    result= "Less than -1"
print(x)
print(result)

0.2894268099728591
Between -1 & 1


In [117]:
result = None
x = randn()
if x > 1 :
  result= "Greater than 1"
elif x>=-1:
    result= "Between -1 & 1"
else:
    result= "Less than -1"
print("Hello Python")
print(x)
print(result)

Hello Python
-0.4287788462509559
Between -1 & 1


In [91]:
x=randn()
if x>1:
  result="Greater than 1"
print(x)
print(result)

0.9531962150565247
Greater than 1


In [119]:
result = None
x = randn()
if x > 1 :
  result= "Greater than 1"
else:
  if x>-1:
    result= "Between -1 & 1"
  else:
    result= "Less than -1"
    print("Hello Python")
print(x)
print(result)

Hello Python
-1.3718851060678268
Less than -1


In [121]:
list1=["Brad",20,45.6,True]

In [122]:
list1[1]

20

In [124]:
list2=[4 ,"thanks",list1]
list2[2]

['Brad', 20, 45.6, True]

In [127]:
list1[2]=100

In [129]:
list1

['Brad', 20, 100, True]

In [130]:
LETTERS=['A','B','C','D','E','F','G','H','I','J']

In [131]:
LETTERS[1:6]

['B', 'C', 'D', 'E', 'F']

In [132]:
LETTERS[-1]

'J'

In [133]:
LETTERS[0:8]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [134]:
LETTERS[1:8:2]

['B', 'D', 'F', 'H']

In [135]:
LETTERS[-9:-1:2]

['B', 'D', 'F', 'H']

In [137]:
LETTERS[1::2]

['B', 'D', 'F', 'H', 'J']

In [138]:
LETTERS[::3]

['A', 'D', 'G', 'J']

In [139]:
LETTERS[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [140]:
LETTERS[7:]

['H', 'I', 'J']

In [141]:
tuple1=(56,72, "Brad")

In [142]:
tuple1[1]

72

In [144]:
list(range(30,41))

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [145]:
mylist1=list(range(30,41))

In [146]:
len(mylist1)

11

In [147]:
type(mylist1)

list

In [148]:
max(mylist1)

40

In [149]:
min(mylist1)

30

In [150]:
max('processwhirl')

'w'

In [151]:
min('processwhirl')

'c'

In [152]:
list5=[1,"Brad",30.6,True]

In [153]:
a=np.array(list5)

In [154]:
a

array(['1', 'Brad', '30.6', 'True'], dtype='<U32')

In [155]:
list6=[1,30.6,True]

In [156]:
b=np.array(list6)

In [157]:
b

array([ 1. , 30.6,  1. ])

In [158]:
list7=[1,True]

In [159]:
c=np.array(list7)
c

array([1, 1])

In [160]:
list8=[True]
d=np.array(list8)
d

array([ True])

In [161]:
#Hierarchy of datatype = strings ,float ,integer,boolean